config_setting(
    name = "torch_backend_rocm",
    define_values = {
        "torch_backend": "rocm",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "torch_backend_cuda",
    define_values = {
        "torch_backend": "cuda",
    },
    visibility = ["//visibility:public"],
)
