#!/bin/bash
set -e
SCRIPT_DIR=$(dirname $(realpath $0))

source "${SCRIPT_DIR}"/.bazel_setup.sh


BAZEL_FLAGS="${BAZEL_FLAGS} --config=debug --cpu=${CPU}"

TARGET="$@"
if [ -z "${TARGET}" ]; then
  TARGET="//..."
fi
bazelisk build ${BAZEL_FLAGS} ${TARGET}
