#!/bin/bash
set -e
SCRIPT_DIR=$(dirname $(realpath $0))

source "${SCRIPT_DIR}"/.bazel_setup.sh

BAZEL_FLAGS="${BAZEL_FLAGS} --config=debug"

TARGET="$@"
if [ -z "${TARGET}" ]; then
  TARGET="//..."
fi
# --build_tag_filters=-python-wheel 
bazelisk build ${BAZEL_FLAGS} ${TARGET}
