#!/bin/bash

SCRIPT_DIR=$(dirname $(realpath $0))

source "${SCRIPT_DIR}"/.bazel_setup.sh

BAZEL_FLAGS="${BAZEL_FLAGS} --config=release --cpu=${CPU}"

TARGET="$@"
if [ -z "${TARGET}" ]; then
  TARGET="//..."
fi

bazelisk build ${BAZEL_FLAGS} ${TARGET}

# Ensure the HockeyMOM extension is linked into the workspace
# so that `import hockeymom._hockeymom` works outside Bazel.
# bazelisk run ${BAZEL_FLAGS} //hockeymom:link_ext
