_workspace_name = "test"
workspace(name = _workspace_name)

local_repository(
    name = "com_extension_dev",
    path = "/opt/nvidia/graph-composer/extension-dev"
)

load(
    "@com_extension_dev//build:graph_extension.bzl",
    "graph_nvidia_extension",
)

load("@com_extension_dev//build/toolchain:toolchain.bzl", "toolchain_configure")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

toolchain_configure(name = "toolchain")

# Package created from - https://github.com/jbeder/yaml-cpp.git
# commit = "9a3624205e8774953ef18f57067b3426c1c5ada6"
# http_archive(
#     name = "yaml-cpp",
#     build_file = "@com_extension_dev//build:third_party/yaml-cpp.BUILD",
#     strip_prefix = "yaml-cpp-9a3624205e8774953ef18f57067b3426c1c5ada6",
#     url = "https://urm.nvidia.com/artifactory/sw-isaac-gxf-generic-local/dependencies/external/yaml-cpp/9a3624205e8774953ef18f57067b3426c1c5ada6.tar.gz",
#     sha256 = "e39f54bd2927692603378e373009e56b4891701cee8af7c27370c36978a43ffa",
#     type = "tar.gz",
# )

new_git_repository(
    name="yaml-cpp",
    commit="9a3624205e8774953ef18f57067b3426c1c5ada6",
    remote="https://github.com/jbeder/yaml-cpp.git",
    build_file="@com_extension_dev//build:third_party/yaml-cpp.BUILD",
)

# Package created from - https://github.com/bazelbuild/rules_python
# version - 0.1.0
# http_archive(
#     name = "rules_python",
#     url = "https://urm.nvidia.com/artifactory/sw-isaac-gxf-generic-local/dependencies/external/bazelbuild/rules_python/rules_python-0.1.0.tar.gz",
#     sha256 = "b6d46438523a3ec0f3cead544190ee13223a52f6a6765a29eae7b7cc24cc83a0",
# )

git_repository(
    name="rules_python",
    remote="https://github.com/bazelbuild/rules_python.git",
    tag="0.1.0",  # Use the tag corresponding to version 0.1.0
)

# Package created from - https://github.com/Neargye/magic_enum
# version - 0.9.3
# http_archive(
#     name = "magic_enum",
#     strip_prefix = "magic_enum-0.9.3",
#     urls = ["https://urm.nvidia.com/artifactory/sw-isaac-gxf-generic-local/dependencies/external/magic_enum/v0.9.3.zip"],
# )

git_repository(
    name="magic_enum",
    remote="https://github.com/Neargye/magic_enum.git",
    tag="v0.9.3",  # Use the tag corresponding to version 0.9.3
    strip_prefix="",  # No need for strip_prefix since Git directly clones the repository
)

graph_nvidia_extension(
    name = "StandardExtension",
    version = "2.6.0",
)
