load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "bytetrack",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    includes = ["."],
    visibility = ["//visibility:public"],
)
