#
#
#

# load("@com_extension_dev//build:graph_extension.bzl", "graph_cc_extension")
# load("@com_extension_dev//build:registry.bzl", "register_extension")

# exports_files(["LICENSE"])

# graph_cc_extension(
#     name="hockey_mom",
#     srcs=[
#         "HockeyMom.cpp",
#         "hockey_mom.cpp",
#     ],
#     hdrs=[
#         "HockeyMom.hpp",
#     ],
#     deps=[
#         "@StandardExtension",
#     ],
# )

# register_extension(
#     name="register_hockeymom_ext",
#     badges=[""],
#     extension="hockey_mom",
#     labels=[
#         "nvidia",
#         "gpu",
#     ],
#     ngc_dependencies={
#         "StandardExtension": "2.6.0",
#     },
#     priority="1",
#     git_repository="",
#     url="www.example.com",
#     uuid="eab0452c-34f8-4520-9cc8-b2ed347240a2",
#     version="0.0.1",
#     visibility=["//visibility:public"],
# )
