exports_files([
    "Cargo.toml",
])

filegroup(
    name = "sources",
    srcs = glob([
        "Cargo.toml",
        "Cargo.lock",
        "src/**/*.rs",
    ], allow_empty = True),
)

genrule(
    name = "hm-ui",
    srcs = [
        "Cargo.toml",
        ":sources",
    ],
    outs = ["hm-ui-bin"],
    cmd = """
set -eu
export CARGO_HOME="$$(pwd)/.cargo-home"
export CARGO_TARGET_DIR="$$(pwd)/.cargo-target"
cargo build --locked --manifest-path $(location Cargo.toml) --release
cp "$$CARGO_TARGET_DIR/release/hm-ui" "$@"
""",
    executable = True,
    visibility = ["//visibility:public"],
)
